/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/news': typeof NewsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/news': typeof NewsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronicle': typeof ChronicleRoute
  '/news': typeof NewsRouteWithChildren
  '/rules': typeof RulesRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chronicle'
    | '/news'
    | '/rules'
    | '/api/chat'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chronicle' | '/news' | '/rules' | '/api/chat' | '/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/chronicle'
    | '/news'
    | '/rules'
    | '/api/chat'
    | '/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChronicleRoute: typeof ChronicleRoute
  NewsRoute: typeof NewsRouteWithChildren
  RulesRoute: typeof RulesRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChronicleRoute: ChronicleRoute,
  NewsRoute: NewsRouteWithChildren,
  RulesRoute: RulesRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
