/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebEncryptionRouteImport } from './routes/web-encryption'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ImageGeneratorRouteImport } from './routes/image-generator'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as AiLuxRouteImport } from './routes/ai-lux'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAiLuxRouteImport } from './routes/api/ai-lux'

const WebEncryptionRoute = WebEncryptionRouteImport.update({
  id: '/web-encryption',
  path: '/web-encryption',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGeneratorRoute = ImageGeneratorRouteImport.update({
  id: '/image-generator',
  path: '/image-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLuxRoute = AiLuxRouteImport.update({
  id: '/ai-lux',
  path: '/ai-lux',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiLuxRoute = ApiAiLuxRouteImport.update({
  id: '/api/ai-lux',
  path: '/api/ai-lux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-lux': typeof AiLuxRoute
  '/chronicle': typeof ChronicleRoute
  '/image-generator': typeof ImageGeneratorRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/rules': typeof RulesRoute
  '/web-encryption': typeof WebEncryptionRoute
  '/api/ai-lux': typeof ApiAiLuxRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-lux': typeof AiLuxRoute
  '/chronicle': typeof ChronicleRoute
  '/image-generator': typeof ImageGeneratorRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/rules': typeof RulesRoute
  '/web-encryption': typeof WebEncryptionRoute
  '/api/ai-lux': typeof ApiAiLuxRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-lux': typeof AiLuxRoute
  '/chronicle': typeof ChronicleRoute
  '/image-generator': typeof ImageGeneratorRoute
  '/news': typeof NewsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/rules': typeof RulesRoute
  '/web-encryption': typeof WebEncryptionRoute
  '/api/ai-lux': typeof ApiAiLuxRoute
  '/api/chat': typeof ApiChatRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-lux'
    | '/chronicle'
    | '/image-generator'
    | '/news'
    | '/projects'
    | '/rules'
    | '/web-encryption'
    | '/api/ai-lux'
    | '/api/chat'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-lux'
    | '/chronicle'
    | '/image-generator'
    | '/news'
    | '/projects'
    | '/rules'
    | '/web-encryption'
    | '/api/ai-lux'
    | '/api/chat'
    | '/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-lux'
    | '/chronicle'
    | '/image-generator'
    | '/news'
    | '/projects'
    | '/rules'
    | '/web-encryption'
    | '/api/ai-lux'
    | '/api/chat'
    | '/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiLuxRoute: typeof AiLuxRoute
  ChronicleRoute: typeof ChronicleRoute
  ImageGeneratorRoute: typeof ImageGeneratorRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RulesRoute: typeof RulesRoute
  WebEncryptionRoute: typeof WebEncryptionRoute
  ApiAiLuxRoute: typeof ApiAiLuxRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-encryption': {
      id: '/web-encryption'
      path: '/web-encryption'
      fullPath: '/web-encryption'
      preLoaderRoute: typeof WebEncryptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-generator': {
      id: '/image-generator'
      path: '/image-generator'
      fullPath: '/image-generator'
      preLoaderRoute: typeof ImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lux': {
      id: '/ai-lux'
      path: '/ai-lux'
      fullPath: '/ai-lux'
      preLoaderRoute: typeof AiLuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-lux': {
      id: '/api/ai-lux'
      path: '/api/ai-lux'
      fullPath: '/api/ai-lux'
      preLoaderRoute: typeof ApiAiLuxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiLuxRoute: AiLuxRoute,
  ChronicleRoute: ChronicleRoute,
  ImageGeneratorRoute: ImageGeneratorRoute,
  NewsRoute: NewsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RulesRoute: RulesRoute,
  WebEncryptionRoute: WebEncryptionRoute,
  ApiAiLuxRoute: ApiAiLuxRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
